### ISSUE TITLE
Only add LIMIT 5 to the CLI on select queries if no limit set, and maybe default to 25

### ISSUE THREAD

**Issue by qorrect** [qorrect/PyPrql#12]

**Comment by rbpatt2019** [comment]
So the initial fix is as simple as checking whether `SELECT` is in the generated SQL query or not.
Interestingly,
this works,
but triggers the non-fatal error below:

```shell
Exception when handling the input: This result object does not return rows. It has been closed automatically.,ResourceClosedError('This result object does not return rows. It has been closed automatically.')
Continuing...
```

I'm pretty sure this is just SQLAlchemy letting us know that creating a table doesn't create rows.
Given thats the expected behaviour,
though,
I'm wondering if we can catch this and prevent it from dumping to the screen.

**Comment by qorrect** [comment]
I wonder if SQLAlchemy has different commands for executing INSERTS or queries ?  I've never used it before
